spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret=${JWT_SECRET}
jwt.expire-time=${JWT_EXPIRE_TIME:86400000}